com:
  insilicosoft:
    actuator:
      username: actuator-user
      password: actuator-password
    executor:
      core-pool-size: 2
      max-pool-size: 2
      queue-capacity: 50
      thread-name-prefix: ~Async-dflt-

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - metrics
        - prometheus
  info:
    git:
      enabled: true
      mode: full
  observations:
    annotations:
      enabled: true

server:
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  port: 9002
  shutdown: graceful

spring:
  application:
    name: rip-svc
  cloud:
    stream:
      bindings:
        # Name below referenced internally and by StreamBridge
        simulation-input:
          destination: simulation-invoke
  datasource:
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
    password: password
    url: jdbc:postgresql://localhost:5432/portaldb
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Portal
  servlet:
    # https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.html
    multipart:
      # Max size for uploaded files
      max-file-size: 1MB
      # Max size for a multipart/form-data request (inc. file uploads)
      max-request-size: 1MB
      # Files stored in memory up to this amount (thereafter stored on disk).
      file-size-threshold: 250KB
