apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: simulation-config
    files:
      - application.yml

generatorOptions:
  #disableNameSuffixHash: true
  labels:
    app: simulation-svc
